### ISSUE TITLE
issue with jquery.ticker.js/newsflash_viewlet.js

### ISSUE THREAD

**Issue by saibatizoku** [collective/collective.newsflash#1]
Resource interpreted as Script but transferred with MIME type text/plain.
helper:8Viewport argument value "device-width;" for key "width" not recognized. Content ignored.
helper:8Viewport argument value "0.6666;" for key "initial-scale" was truncated to its numeric prefix.
helper:8Viewport argument value "1.0;" for key "maximum-scale" was truncated to its numeric prefix.
jquery.ticker.js:25Uncaught TypeError: Cannot read property 'tagName' of undefined
$.fn.tickerjquery.ticker.js:25
(anonymous function)newsflash_viewlet.js:10
b.extend.readyjquery-cachekey8542.js:39
ujquery-cachekey8542.js:47

**Comment by hvelarde** [comment]
I think this was fixed in 89b14af3e79231bbeec317ed88fb2bcaa8febab8
