### ISSUE TITLE
avoid automatic portlet installation?

### ISSUE THREAD

**Issue by hvelarde** [collective/collective.newsflash#7]
should we include the portlet, but not to install it automatically?

**Comment by jpgimenez** [comment]
Why there is a portlet? just to show the "Manage news flashes" link? couldn't that be resolved with a link in the footer of the viewlet?

**Comment by hvelarde** [comment]
the viewlet is not visible if there's no content; but now that you mention it; that could be a nice enhancement :-)

**Comment by jpgimenez** [comment]
+1
IMHO the viewlet should be visible if you have rights to add news flashes, even if there is no content to show... just to give you the choice to add some...

**Comment by hvelarde** [comment]
a new enhancement is open as #8
